[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oracle = "LuS6XnQ3qNXqNQvAJ3akXnEJRBv9XNoUricjMgTyCxX"
oracle_v3 = "8gLZV8k3R6JrAs5BZzyyZQikjEfqvJjAz8PxbiYmz2Kb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.mainnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
